/**
 * stm32f0_discovery.ld
 *
 * Copyright (C) 2023 Mateusz Stadnik <matgla@live.com>
 *
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version
 * 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General
 * Public License along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

MEMORY
{
  rom(rx) : ORIGIN = 0x08000000, LENGTH = 128K
  ram(rwx) : ORIGIN = 0x20000000, LENGTH = 16K
}

_heap_size = 0x2000;

INCLUDE ./cortex-m-generic.ld

SECTIONS 
{
.heap :
{
  . = ALIGN(8);
  PROVIDE(_heap_start = .);
  . = . + _heap_size;
  . = ALIGN(8);
  PROVIDE(_heap_end = .);
} >ram
}
