name: YasLD - Renode Emulation Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  execute_renode_tests:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/matgla/Yasld:0.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare project
        shell: bash
        run: |
          mkdir build
      - name: Generate project 
        shell: bash
        working-directory: build
        run: |
          cmake ..
      - name: Execute tests 
        shell: bash
        working-directory: build
        run: |
          make -j$(nproc) run_st


